# Generated by Django 5.1 on 2024-10-17 12:51

import django.db.models.deletion
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10, unique=True)),
                ('plan', models.CharField(choices=[('A', 'PlanA'), ('B', 'PlanB'), ('C', 'PlanC')], max_length=1)),
                ('access_roles', models.CharField(choices=[('L', 'Loader'), ('P', 'Planner'), ('H', 'Leadership')], max_length=1)),
                ('standard_container_type', models.CharField(choices=[('Gen20F', 'General 20 ft container'), ('Gen40F', 'General 40 ft container'), ('High40F', 'HighCube 40 ft container')], max_length=20)),
                ('standard_source', models.CharField(choices=[], max_length=100)),
                ('standard_destination', models.CharField(choices=[], max_length=100)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('shipping_location', models.JSONField(default=list)),
                ('destination_location', models.JSONField(default=list)),
                ('container_type', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('isVerified', models.BooleanField(default=False)),
                ('otp_sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('container_name', models.CharField(max_length=50)),
                ('container_volume', models.FloatField(default=0)),
                ('container_length', models.FloatField()),
                ('container_width', models.FloatField()),
                ('container_height', models.FloatField()),
                ('payload_capacity', models.FloatField(default=0)),
                ('container_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='', max_length=100)),
                ('volume_capacity', models.FloatField(default=0)),
                ('seperator_pallet', models.BooleanField(default=False)),
                ('door_opening_width', models.FloatField(default=0)),
                ('door_opening_length', models.FloatField(default=0)),
                ('cubic_capacity', models.FloatField(default=0)),
                ('tare_weight', models.FloatField(default=0)),
                ('max_gross_weight', models.FloatField(default=0)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('product_hierarchy', models.CharField(max_length=100)),
                ('source_location', models.CharField(max_length=100)),
                ('shipping_point', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('planned_start_date', models.DateField()),
                ('planned_delivery_date', models.DateField(blank=True, null=True)),
                ('order_number', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.company')),
                ('container', models.ManyToManyField(related_name='orders', to='home.container')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku_code', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('sku_name', models.CharField(max_length=50, unique=True)),
                ('sku_description', models.TextField()),
                ('sku_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('gross_weight', models.FloatField()),
                ('net_weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('numberOfCases', models.FloatField(default=0)),
                ('tiltAllowed', models.BooleanField(default=False)),
                ('product_hierarchy', models.TextField()),
                ('incompatibility', models.CharField(max_length=100)),
                ('max_stack_height', models.IntegerField()),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SKU', to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sku')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='skus',
            field=models.ManyToManyField(related_name='orders', through='home.OrderSKU', to='home.sku'),
        ),
        migrations.AddField(
            model_name='company',
            name='SKUs',
            field=models.ManyToManyField(related_name='companies_as_SKU', to='home.sku'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(default='000000', max_length=10, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('OptipackTeam', 'OptipackTeam'), ('Company_SuperAdmin', 'Company_SuperAdmin'), ('Company_Admin', 'Company_Admin'), ('Company_loader', 'Company_loader'), ('Company_planner', 'Company_planner'), ('None', 'None')], max_length=20)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_status', models.CharField(choices=[('Exp', 'expired'), ('Active', 'Active'), ('Dormant', 'Dormant')], max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('user_image', models.FileField(blank=True, null=True, storage=home.models.CustomS3Storage(), upload_to='')),
                ('user_image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('company', models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='home.company')),
            ],
            options={
                'unique_together': {('user_id', 'email_id')},
            },
        ),
        migrations.CreateModel(
            name='LoadPlan',
            fields=[
                ('plan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('utilization', models.FloatField()),
                ('volume_untilized', models.FloatField()),
                ('volume_available', models.FloatField()),
                ('load_details', models.TextField()),
                ('unplanned_load', models.TextField()),
                ('image_top', models.ImageField(upload_to='top_images')),
                ('image_bottom', models.ImageField(upload_to='bottom_images')),
                ('image_left', models.ImageField(upload_to='left_images')),
                ('image_right', models.ImageField(upload_to='right_images')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_plan', to='home.order')),
                ('orderSKU', models.ManyToManyField(related_name='load_plan', to='home.ordersku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_plan', to='home.users')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='home.company')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='home.dashboard')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='home.usertype')),
            ],
            options={
                'unique_together': {('company', 'user_type', 'dashboard')},
            },
        ),
    ]
