# Generated by Django 5.1 on 2024-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='container_type',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='destination_location',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='shipping_location',
            field=models.JSONField(default=list),
        ),
    ]
