# Generated by Django 5.1 on 2024-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_container_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='cubic_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='door_opening_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='door_opening_width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='max_gross_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='payload_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='tare_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='volume_capacity',
            field=models.FloatField(default=0),
        ),
    ]
