# Generated by Django 5.1 on 2024-09-11 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_company_standard_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('isVerified', models.BooleanField(default=False)),
                ('otp_sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
