# Generated by Django 5.1 on 2024-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_container_container_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('OptipackTeam', 'OptipackTeam'), ('Company_SuperAdmin', 'Company_SuperAdmin'), ('Company_Admin', 'Company_Admin'), ('Company_loader', 'Company_loader'), ('Company_planner', 'Company_planner'), ('None', 'None')], max_length=20),
        ),
    ]
