# Generated by Django 5.1 on 2024-09-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_users_first_login_alter_container_container_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SKU', to='home.company'),
        ),
        migrations.AddField(
            model_name='sku',
            name='numberOfCases',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='tiltAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
