# Generated by Django 5.1 on 2024-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_otpregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
